// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: lib/guest/guest.proto

package guest

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_lib_guest_guest_proto struct{}

func (drpcEncoding_File_lib_guest_guest_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_lib_guest_guest_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_lib_guest_guest_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_lib_guest_guest_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_lib_guest_guest_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCGuestServiceClient interface {
	DRPCConn() drpc.Conn

	Exec(ctx context.Context) (DRPCGuestService_ExecClient, error)
	CopyToGuest(ctx context.Context) (DRPCGuestService_CopyToGuestClient, error)
	CopyFromGuest(ctx context.Context, in *CopyFromGuestRequest) (DRPCGuestService_CopyFromGuestClient, error)
	StatPath(ctx context.Context, in *StatPathRequest) (*StatPathResponse, error)
}

type drpcGuestServiceClient struct {
	cc drpc.Conn
}

func NewDRPCGuestServiceClient(cc drpc.Conn) DRPCGuestServiceClient {
	return &drpcGuestServiceClient{cc}
}

func (c *drpcGuestServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcGuestServiceClient) Exec(ctx context.Context) (DRPCGuestService_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, "/guest.GuestService/Exec", drpcEncoding_File_lib_guest_guest_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcGuestService_ExecClient{stream}
	return x, nil
}

type DRPCGuestService_ExecClient interface {
	drpc.Stream
	Send(*ExecRequest) error
	Recv() (*ExecResponse, error)
}

type drpcGuestService_ExecClient struct {
	drpc.Stream
}

func (x *drpcGuestService_ExecClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcGuestService_ExecClient) Send(m *ExecRequest) error {
	return x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (x *drpcGuestService_ExecClient) Recv() (*ExecResponse, error) {
	m := new(ExecResponse)
	if err := x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcGuestService_ExecClient) RecvMsg(m *ExecResponse) error {
	return x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (c *drpcGuestServiceClient) CopyToGuest(ctx context.Context) (DRPCGuestService_CopyToGuestClient, error) {
	stream, err := c.cc.NewStream(ctx, "/guest.GuestService/CopyToGuest", drpcEncoding_File_lib_guest_guest_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcGuestService_CopyToGuestClient{stream}
	return x, nil
}

type DRPCGuestService_CopyToGuestClient interface {
	drpc.Stream
	Send(*CopyToGuestRequest) error
	CloseAndRecv() (*CopyToGuestResponse, error)
}

type drpcGuestService_CopyToGuestClient struct {
	drpc.Stream
}

func (x *drpcGuestService_CopyToGuestClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcGuestService_CopyToGuestClient) Send(m *CopyToGuestRequest) error {
	return x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (x *drpcGuestService_CopyToGuestClient) CloseAndRecv() (*CopyToGuestResponse, error) {
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CopyToGuestResponse)
	if err := x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcGuestService_CopyToGuestClient) CloseAndRecvMsg(m *CopyToGuestResponse) error {
	if err := x.CloseSend(); err != nil {
		return err
	}
	return x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (c *drpcGuestServiceClient) CopyFromGuest(ctx context.Context, in *CopyFromGuestRequest) (DRPCGuestService_CopyFromGuestClient, error) {
	stream, err := c.cc.NewStream(ctx, "/guest.GuestService/CopyFromGuest", drpcEncoding_File_lib_guest_guest_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcGuestService_CopyFromGuestClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCGuestService_CopyFromGuestClient interface {
	drpc.Stream
	Recv() (*CopyFromGuestResponse, error)
}

type drpcGuestService_CopyFromGuestClient struct {
	drpc.Stream
}

func (x *drpcGuestService_CopyFromGuestClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcGuestService_CopyFromGuestClient) Recv() (*CopyFromGuestResponse, error) {
	m := new(CopyFromGuestResponse)
	if err := x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcGuestService_CopyFromGuestClient) RecvMsg(m *CopyFromGuestResponse) error {
	return x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (c *drpcGuestServiceClient) StatPath(ctx context.Context, in *StatPathRequest) (*StatPathResponse, error) {
	out := new(StatPathResponse)
	err := c.cc.Invoke(ctx, "/guest.GuestService/StatPath", drpcEncoding_File_lib_guest_guest_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCGuestServiceServer interface {
	Exec(DRPCGuestService_ExecStream) error
	CopyToGuest(DRPCGuestService_CopyToGuestStream) error
	CopyFromGuest(*CopyFromGuestRequest, DRPCGuestService_CopyFromGuestStream) error
	StatPath(context.Context, *StatPathRequest) (*StatPathResponse, error)
}

type DRPCGuestServiceUnimplementedServer struct{}

func (s *DRPCGuestServiceUnimplementedServer) Exec(DRPCGuestService_ExecStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCGuestServiceUnimplementedServer) CopyToGuest(DRPCGuestService_CopyToGuestStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCGuestServiceUnimplementedServer) CopyFromGuest(*CopyFromGuestRequest, DRPCGuestService_CopyFromGuestStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCGuestServiceUnimplementedServer) StatPath(context.Context, *StatPathRequest) (*StatPathResponse, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCGuestServiceDescription struct{}

func (DRPCGuestServiceDescription) NumMethods() int { return 4 }

func (DRPCGuestServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/guest.GuestService/Exec", drpcEncoding_File_lib_guest_guest_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCGuestServiceServer).
					Exec(
						&drpcGuestService_ExecStream{in1.(drpc.Stream)},
					)
			}, DRPCGuestServiceServer.Exec, true
	case 1:
		return "/guest.GuestService/CopyToGuest", drpcEncoding_File_lib_guest_guest_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCGuestServiceServer).
					CopyToGuest(
						&drpcGuestService_CopyToGuestStream{in1.(drpc.Stream)},
					)
			}, DRPCGuestServiceServer.CopyToGuest, true
	case 2:
		return "/guest.GuestService/CopyFromGuest", drpcEncoding_File_lib_guest_guest_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCGuestServiceServer).
					CopyFromGuest(
						in1.(*CopyFromGuestRequest),
						&drpcGuestService_CopyFromGuestStream{in2.(drpc.Stream)},
					)
			}, DRPCGuestServiceServer.CopyFromGuest, true
	case 3:
		return "/guest.GuestService/StatPath", drpcEncoding_File_lib_guest_guest_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCGuestServiceServer).
					StatPath(
						ctx,
						in1.(*StatPathRequest),
					)
			}, DRPCGuestServiceServer.StatPath, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterGuestService(mux drpc.Mux, impl DRPCGuestServiceServer) error {
	return mux.Register(impl, DRPCGuestServiceDescription{})
}

type DRPCGuestService_ExecStream interface {
	drpc.Stream
	Send(*ExecResponse) error
	Recv() (*ExecRequest, error)
}

type drpcGuestService_ExecStream struct {
	drpc.Stream
}

func (x *drpcGuestService_ExecStream) Send(m *ExecResponse) error {
	return x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{})
}

func (x *drpcGuestService_ExecStream) Recv() (*ExecRequest, error) {
	m := new(ExecRequest)
	if err := x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcGuestService_ExecStream) RecvMsg(m *ExecRequest) error {
	return x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{})
}

type DRPCGuestService_CopyToGuestStream interface {
	drpc.Stream
	SendAndClose(*CopyToGuestResponse) error
	Recv() (*CopyToGuestRequest, error)
}

type drpcGuestService_CopyToGuestStream struct {
	drpc.Stream
}

func (x *drpcGuestService_CopyToGuestStream) SendAndClose(m *CopyToGuestResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

func (x *drpcGuestService_CopyToGuestStream) Recv() (*CopyToGuestRequest, error) {
	m := new(CopyToGuestRequest)
	if err := x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcGuestService_CopyToGuestStream) RecvMsg(m *CopyToGuestRequest) error {
	return x.MsgRecv(m, drpcEncoding_File_lib_guest_guest_proto{})
}

type DRPCGuestService_CopyFromGuestStream interface {
	drpc.Stream
	Send(*CopyFromGuestResponse) error
}

type drpcGuestService_CopyFromGuestStream struct {
	drpc.Stream
}

func (x *drpcGuestService_CopyFromGuestStream) Send(m *CopyFromGuestResponse) error {
	return x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{})
}

type DRPCGuestService_StatPathStream interface {
	drpc.Stream
	SendAndClose(*StatPathResponse) error
}

type drpcGuestService_StatPathStream struct {
	drpc.Stream
}

func (x *drpcGuestService_StatPathStream) SendAndClose(m *StatPathResponse) error {
	if err := x.MsgSend(m, drpcEncoding_File_lib_guest_guest_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
